spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**

# 启动时显示的debug信息 控制
#logging:
#  level:
#    root:  ERROR
#    org.springframework:  ERROR
#    org.mybatis:  ERROR
#    com.mall.core:  DEBUG