spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: /data/mall/tmp/multipart/
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**

server:
  tomcat:
    basedir: /data/mall/tmp/tomcat/