spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 10086

#logging:
#  level:
#    root:  ERROR
#    org.springframework:  ERROR
#    org.mybatis:  ERROR
#    com.mall.admin:  DEBUG
#    com.mall:  ERROR