spring:
  profiles:
    active: db, core, api
  messages:
    encoding: UTF-8

server:
  # 单独启动此服务时的port
  # 可设置为其他端口 不影响 AllApplication启动的端口
  port: 10086

# 启动时显示的debug信息 控制
logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.mall.api:  DEBUG
    com.mall:  ERROR

